### ISSUE TITLE
fe: main is red on Type Check & Lint — #796 left LocalizedString/string mismatch in tool-classifier.ts

### ISSUE THREAD

**Issue by panghy** [intent-hq/intent#1591]
`main` on `intent-hq/cloudlands-fe` currently fails `pnpm run type-check`, so every PR that updates its branch to latest `main` inherits a red **Type Check & Lint** job.

## Symptom

```
src/lib/components/chat/tool-classifier.ts(1403,7): error TS2322: Type 'string' is not assignable to type 'LocalizedString'.
src/lib/components/chat/tool-classifier.ts(1420,5): error TS2322: Type 'string' is not assignable to type 'LocalizedString'.
```

## Root cause

`cloudlands-fe#796` ("relabel deferred tool-search calls and drop duplicative 'Run' verb", commit `68d859f1`) added two `verb = ''` reassignments inside `terminalDisplay()`. That local is declared as

```ts
let verb = m.chat_toolClassifier_run_label();
```

so TypeScript infers Paraglide's branded `LocalizedString` from the initializer, and the plain-`string` reassignment is rejected. `ToolDisplay.verb` is itself declared `string`, so the widening is the correct intent.

## Why it was not caught

Only `Release-please` runs on push to `main` — the typecheck job runs on `pull_request`, so a merge that is green on its own head SHA can still land a red `main`. It surfaced when PR #794 ran `gh pr update-branch` and picked up `68d859f1`.

## Fix

One-line annotation in `src/lib/components/chat/tool-classifier.ts`:

```ts
let verb: string = m.chat_toolClassifier_run_label();
```

Carried by cloudlands-fe#794 (commit `c274c41b`), which will close this issue on merge. Verified: `pnpm run type-check` passes, `tool-classifier.test.ts` 121/121, `svelte-check` 0 errors, lint clean.

## Reproduction

```bash
git worktree add /tmp/fe-main-check origin/main
cd /tmp/fe-main-check
npx paraglide-js compile --project ./project.inlang --outdir ./src/shared/paraglide
npx tsx scripts/type-check.ts
```

**Comment by panghy** [comment]
Fixed in cloudlands-fe v2.19.0 (beta), bundles intentd v0.6.0.

**Comment by panghy** [comment]
cloudlands-fe v2.19.0 promoted to stable, bundles intentd v0.6.0.
